services:
  backend:
    container_name: ss-backend
    image: ghcr.io/whyredfire/ss-backend:latest
    ports:
      - 8000:8000
    environment:
      DB_CONNECTION: "mongodb://mongodb:27017"
    volumes:
      - ./nltk_data:/root/nltk_data
    restart: unless-stopped

  frontend:
    container_name: ss-frontend
    image: ghcr.io/whyredfire/ss-frontend:latest
    ports:
      - 3000:80
    restart: unless-stopped
    depends_on:
      - backend

  mongodb:
    container_name: ss-mongodb
    image: mongo:latest
    volumes:
      - ./mongodb_data:/data/db
    restart: unless-stopped
    depends_on:
      - backend
