name: Build and Push Docker Image to GHCR

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/docker-build.yaml
      - backend/**/*
      - frontend/**/*
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: ss-frontend
            path: frontend
          - name: ss-backend
            path: backend
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Docker Image for ${{ matrix.name }}
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.path }}
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/whyredfire/${{ matrix.name }}:latest
            ghcr.io/whyredfire/${{ matrix.name }}:${{ github.sha }}
          cache-from: type=gha,scope=${{ matrix.name }}
          cache-to: type=gha,mode=max,scope=${{ matrix.name }}

  update-manifests:
    runs-on: ubuntu-slim
    needs: build-and-push
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Update image tags
        run: |
          yq -i ".spec.template.spec.containers[0].image = \"ghcr.io/whyredfire/ss-frontend:${GITHUB_SHA}\"" k8s/frontend/deployment.yaml
          yq -i ".spec.template.spec.containers[0].image = \"ghcr.io/whyredfire/ss-backend:${GITHUB_SHA}\"" k8s/backend/deployment.yaml

      - name: Commit to repo
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          commit_message: "k8s: Bump images to ${{ github.sha }} [no ci]"
          file_pattern: "k8s/**/deployment.yaml"
